"use strict";

module.exports = [
    "\"You miss 100% of the shots you don't take.\" - Wayne Gretzky",
    "Do you think that smoking drugs is cool?",
    "Do you think that doing alcohol is cool?",
    "Sometimes I'll start a sentence and I don't even know where it's going. I just hope I find it along the way.",
    "I'm not superstitious, but I am a little stitous.",
    "There's such a thing as good grief. Just ask Charlie Brown.",
    "Oh God, my mind is going a mile an hour.",
    "I am Beyoncé, always.",
    "I love Burlington Coat Factory.",
    "PowerPoint. PowerPoint.",
    "I feel like all my kids grew up, and then they married each other, it's every parent's dream.",
    "I DECLARE BANKRUPTCY!",
    "That's what she said.",
    "NO! GOD! NO GOD PLEASE NO! NO! NOOOOOOOOOOOOOOOOOOOO",
    "STANLEY STANLEY YOU WILL NOT DIE STANLEY STANLEY BARACK IS PRESIDENT",
    "I am downloading some n3p music.",
    "WHERE ARE THE TURTLES?!",
    "The worst thing about prison was the dementors.",
    "Occasionally, I'll hit somebody with my car. So sue me.",
    "If I had a gun with two bullets and I was in a room with Hitler, Bin Laden, and Toby, I would shoot Toby twice.",
    "Just tell him to call me as asap as possible.",
    "It's a good thing Russia doesn't exist anymore.",
    "Well, happy birthday, Jesus. Sorry your party's so lame.",
    "You know what's gonna be on your tombstone? \"Loser.\"",
    "I love inside jokes. Love to be a part of one someday.",
    "Would I rather be feared or loved? Easy, both. I want people to be afraid of how much they love me.",
    "I like waking up to the smell of bacon.",
    "I don't want to do anything. I'm dying.",
    "I. Understand. Nothing.",
    "I feel very blessed.",
    "I am dead inside.",
    "I'm running away from my responsibilities.",
    "You are a thief of joy.",
    "PARKOUR.",
    "Okay, I am going to throw up.",
    "I knew exactly what to do. But in a much more real sense, I had no idea what to do.",
    "I don't need fresh air. Because I have the freshest air around. A/C.",
    "I'm optimistic, because every day I get a little more desperate.",
    "Maybe there's some sort of animal we can make a sacrifice to.",
    "I've made some empty promises in my life.",
    "I hate looking at your face. I wanna smash it.",
    "Only thing that could make this day better is ice cream.",
    "Gift baskets are... the essence of class and fanciness. They are the ultimate present a person can receive.",
    "Wikipedia is the best thing ever. Anyone in the world can write anything they want about any subject. So you know you are getting the best possible information.",
    "No, I'm not going to tell them about the downsizing. If a patient has cancer, you don't tell them.",
    "An office is for not dying. An office is a place to live life to the fullest, to the max, to... An office is a place where dreams come true.",
    "Make friends first, make sales second, make love third. In no particular order.",
    "Well, it's love at first sight. Actually, it was... No, it was when I heard her voice. It was love at first see with my ears.",
    "Do I need to be liked? Absolutely not. I like to be liked. I enjoy being liked. I have to be liked, but it's not like this compulsive need to be liked, like my need to be praised.",
    "I guess I’ve been working so hard, I forgot what it’s like to be hardly working.",
    "I don't hate it. I just don't like it at all and it's terrible.",
    "I say dance, they say 'How high?'",
    "Fool me once, strike one. Fool me twice, strike three.",
    "I want you to rub butter on my foot...Pam, please? I have Country Crock.",
    "Toby is in HR which technically means he works for corporate. So he's not really a part of our family. Also he's divorced... so he's not really a part of his family.",
    "Jan is cold. If she was sitting across from you on a train and she wasn't moving, you might think she was dead.",
    "I don't come up with this stuff, I just forward it along. You wouldn't arrest the guy who was just passing drugs from one guy to another.",
    "Friends joke with one another. 'Hey, you're poor.' 'Hey, your momma's dead.' That's what friends do.",
    "I would not miss it for the world. But if something else came up I would definitely not go.",
    "Sometimes you have to take a break from being the kind of boss that's always trying to teach people things. Sometimes you just have to be the boss of dancing.",
    "Presents are the best way to show someone how much you care. It's like this tangible thing that you can point to and say, ‘Hey, man, I love you this many dollars worth.’",
    "Hi, I'm Date Mike. Nice to meet me. How do you like your eggs in the morning?",
    "It is St. Patrick's Day….It is the closest that the Irish will ever get to Christmas.",
    "I don't understand. We have a day honoring Martin Luther King, but he didn't even work here.",
    "It's a pimple, Phyllis. Avril Lavigne gets them all the time and she rocks harder than anyone alive.",
    "Don't ever, for any reason, do anything for anyone, for any reason, ever, no matter what. No matter where. Or who, or who you are with, or where you are going or... or where you've been... ever. For any reason, whatsoever.",
    "Abraham Lincoln once said that, 'If you're a racist, I will attack you with the North.' And those are the principles that I carry with me in the workplace.",
    "I’m an early bird and I’m a night owl. So I’m wise and I have worms.",
    "Here it is, heart of New York City, Times Square... named for the good times you have when you're in it.",
    "Webster's Dictionary defines wedding as: The fusing of two metals with a hot torch.",
    "I guess the attitude that I've tried to create here is that I'm a friend first and a boss second and probably an entertainer third.",
    "This is an environment of welcoming and you should just get the hell out of here.",
    "Well, well, well, how the turntables.",
    "You cheated on me? When I specifically asked you not to?",
    "I have got to make sure that YouTube comes down to tape this.",
    "It's simply beyond words. It's incalculable."
];
